select * from customer

--Q1 What is the total revenue generated by male vs female customers
select gender, Sum(purchase_amount) as revenue
from customer
group by gender

--Q2 Which customers used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (Select AVG(purchase_amount) from customer)

--Q3 Which are the top 5 products with th highest average review rating
SELECT TOP 5 item_purchased, Round (Avg(review_rating),2)as "Average Product Rating"
FROM customer
group by item_purchased
ORDER BY avg(review_rating) DESC

--Q4 Compare the average purchase amount between standard and express shipping
Select shipping_type, Avg(purchase_amount) as "Average Purchase Amount"
from customer
WHERE shipping_type IN ('standard', 'express')
group by shipping_type

--Q5 Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers

select subscription_status, Round(Avg(purchase_amount),2) as "Average Purchase Amount", 
Sum(purchase_amount) as "Total Purchase Amount", count(customer_id) as total_customers
from customer
group by subscription_status
order by "Total Purchase Amount", "Average Purchase Amount"

--Q6 Which 5 products have the highest percentage of purchase with discount applied
select Top 5 item_purchased, Round(100*Sum(Case when discount_applied = 'Yes' Then 1 Else 0 End)
/Count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate DESC

--Q7 Segmnt customers into new, returning and loyalbased on their total
--number of previous purchase and show the count of each segment

SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS Loyalty_Tier,
    
    COUNT(customer_id) AS Customer_Count
FROM customer
GROUP BY
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END
ORDER BY Customer_Count DESC;


--Q8. What are th top 3 most purchased products within each category
with item_counts as (
Select item_purchased, category, count(customer_id) as total_orders,
Row_Number() over(partition by category order by count(customer_id) Desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

--Q9 Are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe

select subscription_status, COUNT(customer_id) AS Customer_Count
from customer
where previous_purchases>5
group by subscription_status

--Q10 What is the revenue contribution of each age group

Select age_group, sum(purchase_amount)
from customer
group by age_group
Order by sum(purchase_amount) Desc